# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhqFzf < Formula
  desc ""
  homepage ""
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yumafuu/ghq-fzf/releases/download/v1.0.2/ghq-fzf_1.0.2_darwin_amd64.tar.gz"
      sha256 "481ada2277004439c30fe722e387f7169c57e7b9119c931ad3c1ad74df2db86b"

      def install
        bin.install "_ghq-fzf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yumafuu/ghq-fzf/releases/download/v1.0.2/ghq-fzf_1.0.2_darwin_arm64.tar.gz"
      sha256 "db9955271f6dc4ff4ddffab53a0f91394dc71abdef5609d31296ef538084d494"

      def install
        bin.install "_ghq-fzf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/yumafuu/ghq-fzf/releases/download/v1.0.2/ghq-fzf_1.0.2_linux_amd64.tar.gz"
      sha256 "3807cdd342b94d6885f1ff174baf5969d288c28f0e3bafac2db7b99ab966b5cc"
      def install
        bin.install "_ghq-fzf"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/yumafuu/ghq-fzf/releases/download/v1.0.2/ghq-fzf_1.0.2_linux_arm64.tar.gz"
      sha256 "76a06ce27251248081cbbd2e626dee9efbbe1bf21163f14d322672f211250f2f"
      def install
        bin.install "_ghq-fzf"
      end
    end
  end
end
