# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhqFzf < Formula
  desc ""
  homepage ""
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yumafuu/ghq-fzf/releases/download/v1.0.0/ghq-fzf_1.0.0_darwin_amd64.tar.gz"
      sha256 "5997deffc5cfa863be409abb1cf61f4b276595f15044901f675b1dec86b8a34a"

      def install
        bin.install "_ghq-fzf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yumafuu/ghq-fzf/releases/download/v1.0.0/ghq-fzf_1.0.0_darwin_arm64.tar.gz"
      sha256 "a267ec3ccbbbc8169e9fbeadf40edee3d5e1bf4e451067c0fc311af3bad12f35"

      def install
        bin.install "_ghq-fzf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yumafuu/ghq-fzf/releases/download/v1.0.0/ghq-fzf_1.0.0_linux_amd64.tar.gz"
        sha256 "ccee1fd09d8e564daa8f50b632a2bc56b8053b882cebc9b2b0fcb7947b542159"

        def install
          bin.install "_ghq-fzf"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yumafuu/ghq-fzf/releases/download/v1.0.0/ghq-fzf_1.0.0_linux_arm64.tar.gz"
        sha256 "45105649d0233909bb0a1bd5a0b7f032d10b84eaf74f06649aca73d141ffe6b0"

        def install
          bin.install "_ghq-fzf"
        end
      end
    end
  end
end
