# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S1m < Formula
  desc ""
  homepage ""
  version "0.2.5"

  on_macos do
    on_intel do
      url "https://github.com/yumafuu/s1m/releases/download/v0.2.5/s1m_Darwin_x86_64.tar.gz"
      sha256 "f009712f51a8ebcab65984e8d8941e1d231af8d86dbe9e54f8390e87c2765cde"

      def install
        bin.install "s1m"
      end
    end
    on_arm do
      url "https://github.com/yumafuu/s1m/releases/download/v0.2.5/s1m_Darwin_arm64.tar.gz"
      sha256 "8f653dc3368ccfa8197a24efe3e40573915044d24885821d2d6e97ee75814d69"

      def install
        bin.install "s1m"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yumafuu/s1m/releases/download/v0.2.5/s1m_Linux_x86_64.tar.gz"
        sha256 "366b8ecaa7e9108ed14d3a10429ebccdf5330a0b3fe10fe8385f77b1ca111868"

        def install
          bin.install "s1m"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yumafuu/s1m/releases/download/v0.2.5/s1m_Linux_arm64.tar.gz"
        sha256 "de1293784a16e47c72fb39f387fc29b4552b8286991fc50e5766b6335e280b40"

        def install
          bin.install "s1m"
        end
      end
    end
  end
end
