# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S1m < Formula
  desc ""
  homepage ""
  version "0.2.4"

  on_macos do
    on_intel do
      url "https://github.com/yumafuu/s1m/releases/download/v0.2.4/s1m_Darwin_x86_64.tar.gz"
      sha256 "cffec270782d0f80a01de40caf4d8ac77a2340a5d95f13d1a2821e09e42e2e88"

      def install
        bin.install "s1m"
      end
    end
    on_arm do
      url "https://github.com/yumafuu/s1m/releases/download/v0.2.4/s1m_Darwin_arm64.tar.gz"
      sha256 "deb32eb19d20a3beaa44b6183538de21abde41df5ca2d05957c47652c2113e00"

      def install
        bin.install "s1m"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yumafuu/s1m/releases/download/v0.2.4/s1m_Linux_x86_64.tar.gz"
        sha256 "2f1c02982362030734cdf0215631fb2b89ea599b67a0fc9f58ad3d6037b8170a"

        def install
          bin.install "s1m"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yumafuu/s1m/releases/download/v0.2.4/s1m_Linux_arm64.tar.gz"
        sha256 "7b156c3efa5249fb6cc3aee393c258c9023ecb93ef2a33710fee5a6f1cb961cb"

        def install
          bin.install "s1m"
        end
      end
    end
  end
end
